apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ai-core-platform
type: Opaque
data:
  # Application Secrets
  root-key: RXZlbnRzLmNvbQ== # base64 encoded "Events.com"
  basic-auth-user: YWRtaW4= # base64 encoded "admin"
  basic-auth-pass: ZXZlbnRzLmNvbQ== # base64 encoded "events.com"
