apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-core-platform-sa
  namespace: ai-core-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::194722419261:role/AmazonEKSAutoClusterRole # will change
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-core-platform-role
  namespace: ai-core-platform
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-core-platform-role-binding
  namespace: ai-core-platform
subjects:
  - kind: ServiceAccount
    name: ai-core-platform-sa
roleRef:
  kind: Role
  name: ai-core-platform-role
  apiGroup: rbac.authorization.k8s.io
